### ISSUE TITLE
use official webmock.cr

### ISSUE THREAD

**Issue by alexanderadam** [vonKingsley/hi8.cr#1]
Thank you for hi8! 🙌 

Now [as your PR is merged](https://github.com/manastech/webmock.cr/pull/13#event-1329681387), you fork isn't needed any longer as dependency, right?

**Comment by vonKingsley** [comment]
Awesome thanks for nudging them.  I'll run some tests probably between now and this weekend and if everything is good, I'll remove the dependency.  As for hi8 there are still some options I want to implement, I think i outline the downfalls in the readme.

**Comment by alexanderadam** [comment]
Awesome, you answer fast! Thank you 👍

**Comment by vonKingsley** [comment]
I switched this over to official webmock repo.  I had to set the master branch because there was something weird with the versioning, so I'll keep my eyes open on this for a while and see if anyone has issue.

**Comment by alexanderadam** [comment]
Awesome, this issue can be closed then I guess!?
Have a nice week and again: thank you for hi8!
