### ISSUE TITLE
Allow cassette folders/nesting

### ISSUE THREAD

**Issue by aisrael** [vonKingsley/hi8.cr#4]
##### Background

To better group and isolate cassettes, it would be useful to be able to organize them into nested folders.

##### Sample code

Am thinking along these lines:

```
describe Client do
  describe "get_foo" do
    it "should work" do
      HI8.use_cassette("get_foo/should_work") do
        // ...
```

##### Expected behavior

Should record to `test_dir/cassettes/get_foo/should_work.yml`.

##### Actual behavior

HI8 fails to write the cassette to the filesystem.

**Comment by vonKingsley** [comment]
I agree.  I'll look into this and fix it up sometime this week.

**Comment by vonKingsley** [comment]
This should work now.  If you want to give it a try and let me know if there are any problems

**Comment by aisrael** [comment]
It works! Brilliant!
