### ISSUE TITLE
Custom request matcher

### ISSUE THREAD

**Issue by alexanderadam** [vonKingsley/hi8.cr#6]
First of all: thank you for `hi8.cr`

It would be wonderful if `hi8.cr` would allow custom request matcher.
Maybe like [vcr](https://relishapp.com/vcr/vcr/v/3-0-3/docs/upgrade)

Thank you in advance!

**Comment by vonKingsley** [comment]
The PR looked great, thanks for cleaning up the specs and adding the functionality.  I think we can close this if you think everything looks good.

**Comment by alexanderadam** [comment]
Well, I have to thank _you_! It was a pleasure.
